eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-b:
      path: /api-a/**
      serviceId: service-ribbon
    api-c:
      path: /api-b/**
      serviceId: service-feign
  host:
      socket-timeout-millis: 60000
      connect-timeout-millis: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000